
import { Event, EventCategory, User } from "./types";

// Sample Cities
export const CITIES = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Philadelphia",
  "Phoenix",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
];

// Sample Interests
export const INTERESTS = [
  "Music",
  "Travel",
  "Technology",
  "Food",
  "Sports",
  "Art",
  "Photography",
  "Fashion",
  "Gaming",
  "Reading",
  "Writing",
  "Fitness",
  "Outdoor Activities",
  "Movies",
  "Coding",
];

// Sample Event Categories
export const EVENT_CATEGORIES: EventCategory[] = [
  "Music",
  "Travel",
  "Tech",
  "Workshops",
  "All",
];

// Mock Users (for demo purposes)
export const MOCK_USERS: User[] = [
  {
    id: "user1",
    name: "John Doe",
    email: "john@example.com",
    role: "attendee",
    profileImage: "https://ui-avatars.com/api/?name=John+Doe&background=random",
    gender: "Male",
    city: "New York",
    interests: ["Music", "Technology", "Gaming"],
    age: 28,
    budget: 300,
    verified: true,
  },
  {
    id: "user2",
    name: "Jane Smith",
    email: "jane@example.com",
    role: "organizer",
    profileImage: "https://ui-avatars.com/api/?name=Jane+Smith&background=random",
    gender: "Female",
    city: "Los Angeles",
    interests: ["Music", "Art", "Photography"],
    age: 32,
    verified: true,
  },
];

// Mock Events (for demo purposes)
export const MOCK_EVENTS: Event[] = [
  {
    id: "event1",
    title: "Summer Music Festival",
    description: "A three-day music festival featuring top artists from around the world.",
    date: "2025-07-15",
    time: "12:00 PM",
    location: "Central Park, New York",
    price: 150,
    category: "Music",
    imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
    organizerId: "user2",
    organizerName: "Jane Smith",
    attendees: ["user1"],
    capacity: 1000,
  },
  {
    id: "event2",
    title: "Tech Conference 2025",
    description: "Learn about the latest technologies and network with industry professionals.",
    date: "2025-09-20",
    time: "9:00 AM",
    location: "Convention Center, San Francisco",
    price: 250,
    category: "Tech",
    imageUrl: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
    organizerId: "user2",
    organizerName: "Jane Smith",
    attendees: [],
    capacity: 500,
  },
  {
    id: "event3",
    title: "European Travel Tour",
    description: "A two-week guided tour of Europe's most beautiful cities.",
    date: "2025-06-10",
    time: "8:00 AM",
    location: "Paris, France",
    price: 2000,
    category: "Travel",
    imageUrl: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
    organizerId: "user2",
    organizerName: "Jane Smith",
    attendees: [],
    capacity: 20,
  },
  {
    id: "event4",
    title: "Photography Workshop",
    description: "Learn professional photography techniques from industry experts.",
    date: "2025-05-15",
    time: "2:00 PM",
    location: "Gallery Space, Chicago",
    price: 100,
    category: "Workshops",
    imageUrl: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2074&q=80",
    organizerId: "user2",
    organizerName: "Jane Smith",
    attendees: ["user1"],
    capacity: 30,
  },
  {
    id: "event5",
    title: "Jazz Night",
    description: "An evening of jazz music performed by local musicians.",
    date: "2025-05-30",
    time: "8:00 PM",
    location: "Jazz Club, New Orleans",
    price: 50,
    category: "Music",
    imageUrl: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2072&q=80",
    organizerId: "user2",
    organizerName: "Jane Smith",
    attendees: [],
    capacity: 100,
  },
  {
    id: "event6",
    title: "Web Development Bootcamp",
    description: "Intensive coding bootcamp to learn web development from scratch.",
    date: "2025-08-01",
    time: "9:00 AM",
    location: "Tech Hub, Austin",
    price: 500,
    category: "Tech",
    imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2072&q=80",
    organizerId: "user2",
    organizerName: "Jane Smith",
    attendees: [],
    capacity: 50,
  },
];
