// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjhprnoitcfzhoyreeff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqaHBybm9pdGNmemhveXJlZWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDc1NTMsImV4cCI6MjA2MDI4MzU1M30.oBE5g4UJpXRbnZ_eKS3ScoE3NULsg6LG1rrtqjvHDwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);